[package]
name = 'aoc_2015'
version = '0.1.0'
authors = ['Josh Comer <joshjcomer@gmail.com>']
edition = '2018'

[lib]
bench = false

[dependencies]
aoc-runner = '0.3'
aoc-runner-derive = '0.3'
regex = '1.4'
md5 = '0.7'
